### PR TITLE
Cosmetic patch

### PR DESCRIPTION
**Pull request by Jadhielv**
Purely cosmetic patch.

### CODE REVIEW

**Comment by Jadhielv** [comment]
@DannyFeliz If you have time, please check this PR.

**Comment by Jadhielv** [comment]
@MarluanEspiritusanto If you have time, please check this PR.

**Review by JeffreyArt1 — APPROVED** [review]

**Comment by Jadhielv** [comment]
@JeffreyArt1 Do you merge this PR?

**Comment by Jadhielv** [comment]
@MarluanEspiritusanto If you have time, please check this PR.

**Review by JeffreyArt1 — APPROVED** [review]

**Pull request merged**
